"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient("https://oietadzixpglmkiokihj.supabase.co","sb_publishable_lbPUme-0Y7hjHWdcdGS2nA_Miy8rnzx");
export default function AccessPage(){
const [role,setRole]=useState("waiter");
const [staff,setStaff]=useState<any[]>([]);
const [staffId,setStaffId]=useState("");
const [authorized,setAuthorized]=useState(false);
const [loading,setLoading]=useState(true);
const [busy,setBusy]=useState(false);
const [result,setResult]=useState<any>(null);
const [error,setError]=useState("");
useEffect(()=>{(async()=>{const {data}=await db.rpc("mesa_my_access");const ok=data?.role==="owner"||data?.role==="manager";setAuthorized(ok);if(ok){const {data:bootstrap}=await db.rpc("bootstrap_mesa");const list=(bootstrap?.staff||[]);setStaff(list);setStaffId(list[0]?.id||"")}setLoading(false)})()},[]);
const eligible=staff.filter((x:any)=>{const staffRole=String(x.role||"waiter").toLowerCase();return staffRole===role||(role==="cashier"&&["billing","cashier","caja"].includes(staffRole))});
useEffect(()=>{if(!eligible.some((x:any)=>x.id===staffId))setStaffId(eligible[0]?.id||"")},[role,staff]);
const generate=async()=>{setBusy(true);setError("");setResult(null);try{const {data}=await db.auth.getSession();if(!data.session)throw Error("Iniciá sesión como dueño");const response=await db.functions.invoke("mesa-staff-access",{body:{role,staff_id:staffId}});if(response.error){let detail=response.data?.error;try{if(!detail&&response.error.context?.json)detail=(await response.error.context.json()).error}catch{}throw Error(detail||"No se pudo contactar a Supabase. Intentá nuevamente.")}if(!response.data?.email||!response.data?.pin)throw Error(response.data?.error||"La función no devolvió credenciales");setResult(response.data)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
return <main className="mesaAccessPage"><style>{`
.mesaAccessPage{min-height:100vh;background:#f5eee6;color:#090909;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;padding:0 20px 50px;cursor:default}
.mesaAccessPage *{box-sizing:border-box}.mesaAccessPage button,.mesaAccessPage a,.mesaAccessPage select{cursor:pointer!important}
.mesaAccessHeader{height:76px;border-bottom:1px solid #e2d7ca;display:flex;align-items:center;justify-content:space-between;max-width:1200px;margin:auto}
.mesaAccessBrand{display:flex;align-items:center;gap:12px;text-decoration:none;color:#080808;font-size:20px;font-weight:900;letter-spacing:-.05em}.mesaAccessBrand i{font-style:normal;display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:#080808;color:#fff;box-shadow:3px 3px 0 #00ba50;font-size:21px}
.mesaAccessBack{color:#141414;text-decoration:none;border:1px solid #d9cfc4;border-radius:30px;padding:10px 17px;font-weight:750;font-size:13px;background:#fff}
.mesaAccessLayout{max-width:940px;margin:72px auto;display:grid;grid-template-columns:1fr 1.1fr;gap:48px;align-items:start}
.mesaAccessIntro .eyebrow{font-size:11px;letter-spacing:.16em;font-weight:900;color:#a77818}.mesaAccessIntro h1{font-size:clamp(46px,5vw,76px);letter-spacing:-.075em;line-height:.96;margin:16px 0 22px;font-weight:900}.mesaAccessIntro p{color:#655d57;line-height:1.65;font-size:16px;max-width:370px}.mesaAccessStep{display:flex;align-items:center;gap:10px;margin-top:30px;font-size:13px;font-weight:700}.mesaAccessStep i{display:grid;place-items:center;width:27px;height:27px;border-radius:50%;background:#dcfce6;color:#087f36;font-style:normal}
.mesaAccessCard{background:#fff;border:1px solid #e4dcd3;border-radius:24px;padding:32px;box-shadow:7px 7px 0 #0ab957}.mesaAccessCard h2{font-size:24px;letter-spacing:-.04em;margin:0 0 8px}.mesaAccessCard .hint{color:#6f6760;font-size:13px;line-height:1.5;margin:0 0 28px}.mesaAccessCard label{display:block;font-size:12px;font-weight:800;margin-bottom:18px}.mesaAccessCard select{display:block;width:100%;margin-top:9px;padding:14px 12px;border:1px solid #d6cec6;border-radius:11px;background:#fff;color:#111;font-size:14px;outline-offset:3px}.mesaAccessPrimary{background:#050505;color:#fff;border:0;border-radius:12px;padding:15px 19px;font-weight:800;width:100%;font-size:14px}.mesaAccessPrimary:disabled{opacity:.5;cursor:not-allowed!important}.mesaAccessError{margin-top:18px;padding:13px;background:#fff0ef;color:#a71919;border-radius:10px;font-size:13px;line-height:1.5}.mesaAccessResult{margin-top:22px;padding:18px;background:#eaf8ed;border:1px solid #b4e8c4;border-radius:14px}.mesaAccessResult .success{color:#087d34;font-weight:900;font-size:12px;letter-spacing:.06em}.mesaAccessResult .cred{margin:13px 0}.mesaAccessResult .cred span{display:block;color:#48624e;font-size:11px;font-weight:800;margin-bottom:5px}.mesaAccessResult .cred strong{font-size:14px;overflow-wrap:anywhere}.mesaAccessResult .pin strong{font-size:25px;letter-spacing:.08em}.mesaAccessCopy{padding:11px 15px;border-radius:9px;background:#fff;border:1px solid #b8d4c0;font-weight:800;font-size:12px}.mesaAccessFoot{margin:18px 0 0;font-size:12px;color:#6f6760}.mesaAccessFoot a{color:#111;font-weight:800}
@media(max-width:760px){.mesaAccessLayout{grid-template-columns:1fr;margin:40px auto;gap:25px}.mesaAccessIntro h1{font-size:52px}.mesaAccessCard{padding:24px}}
`}</style><header className="mesaAccessHeader"><a className="mesaAccessBrand" href="/"><i>M</i>Mesa</a><a className="mesaAccessBack" href="/">← Volver al panel</a></header><div className="mesaAccessLayout"><div className="mesaAccessIntro"><span className="eyebrow">GESTIÓN DEL EQUIPO</span><h1>Accesos del personal.</h1><p>Un acceso privado para cada mozo, para facturación y para cocina. Vos administrás las credenciales y cada empleado ingresa a su propio panel.</p><div className="mesaAccessStep"><i>✓</i> Accesos vinculados a tu restaurante</div><div className="mesaAccessStep"><i>✓</i> Podés renovar una clave cuando quieras</div></div><section className="mesaAccessCard"><h2>Crear credenciales</h2><p className="hint">Elegí el puesto y luego un empleado de ese sector. Generaremos un usuario y una clave para ingresar.</p>{loading?<p>Cargando personal...</p>:!authorized?<p>Para administrar accesos, primero <a href="/">iniciá sesión como dueño</a>.</p>:<><label>Tipo de acceso<select value={role} onChange={e=>{setRole(e.target.value);setResult(null);setError("")}}><option value="waiter">Mozo</option><option value="cashier">Facturación / Caja</option><option value="kitchen">Cocina</option></select></label><label>Empleado<select value={staffId} onChange={e=>{setStaffId(e.target.value);setResult(null)}}>{eligible.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{eligible.length===0&&<span style={{display:"block",marginTop:8,color:"#9b4b24",fontWeight:500}}>No hay empleados con este puesto. Agregá uno desde Personal.</span>}</label><button className="mesaAccessPrimary" disabled={busy||!staffId} onClick={generate}>{busy?"Generando acceso...":"Generar o renovar clave →"}</button>{error&&<p className="mesaAccessError" role="alert">{error}</p>}{result&&<div className="mesaAccessResult" role="status"><div className="success">✓ ACCESO GENERADO</div><div className="cred"><span>USUARIO</span><strong>{result.email}</strong></div><div className="cred pin"><span>CLAVE PRIVADA</span><strong>{result.pin}</strong></div><button className="mesaAccessCopy" onClick={()=>navigator.clipboard.writeText("Usuario: "+result.email+"\\nClave: "+result.pin+"\\nAcceso: "+location.origin+"/personal")}>Copiar usuario y clave</button><p className="mesaAccessFoot">Guardá estos datos ahora. Al renovar la clave, la anterior deja de funcionar.</p></div>}</>}<p className="mesaAccessFoot">¿Sos empleado? <a href="/personal">Ingresá a tu panel →</a></p></section></div></main>
}