"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
const db=createClient("https://oietadzixpglmkiokihj.supabase.co","sb_publishable_lbPUme-0Y7hjHWdcdGS2nA_Miy8rnzx");
type Booking={id:string;restaurant_id:string;table_id:string;guest_name:string;guest_phone:string;guest_count:number;starts_at:string;status:string;payment_status:string;created_at:string};
export default function MisReservas(){const [restaurants,setRestaurants]=useState<{id:string;name:string}[]>([]),[selected,setSelected]=useState(""),[rows,setRows]=useState<Booking[]>([]),[policy,setPolicy]=useState<{reservation_grace_minutes:number;reservation_alias:string;reservation_min_amount:number}|null>(null),[tables,setTables]=useState<Record<string,number>>({}),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){setLoading(false);return}const {data}=await db.from("restaurant_memberships").select("restaurant_id").eq("user_id",user.id).in("role",["owner","manager"]);const ids=(data||[]).map(x=>x.restaurant_id);if(ids.length){const {data:r}=await db.from("restaurants").select("id,name").in("id",ids);setRestaurants(r||[]);setSelected(ids[0])}setLoading(false)})()},[]);
async function refresh(){if(!selected)return;db.from("mesa_directory_profiles").select("reservation_grace_minutes,reservation_alias,reservation_min_amount").eq("restaurant_id",selected).maybeSingle().then(({data})=>setPolicy(data||null));const [{data,error},{data:t}]=await Promise.all([db.from("mesa_reservations").select("*").eq("restaurant_id",selected).gte("starts_at",new Date(Date.now()-86400000).toISOString()).order("starts_at",{ascending:true}).limit(300),db.from("tables").select("id,number").eq("restaurant_id",selected)]);setRows(data||[]);setTables(Object.fromEntries((t||[]).map(x=>[x.id,x.number])));if(error)setMessage(error.message)}
useEffect(()=>{void refresh()},[selected]);
async function payment(id:string,value:string){const {error}=await db.rpc("mesa_set_reservation_payment",{p_reservation_id:id,p_status:value});setMessage(error?"No se pudo actualizar el pago: "+error.message:"Estado del anticipo actualizado.");if(!error)void refresh()}
function whatsappLink(r:Booking){const digits=r.guest_phone.replace(/\D/g,"");const phone=digits.startsWith("0")?digits.replace(/^0+/,""):digits;const restaurant=restaurants.find(x=>x.id===r.restaurant_id)?.name||"el restaurante";const when=new Date(r.starts_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires",dateStyle:"full",timeStyle:"short"});const pay=r.payment_status==="received"?"Recibimos tu transferencia y verificamos el anticipo.":r.payment_status==="rejected"?"El anticipo no fue acreditado. Contactanos para resolverlo.":"Todavía no verificamos el anticipo por transferencia.";const msg="Hola "+r.guest_name+", te escribimos de "+restaurant+" por tu reserva en MESA.\nFecha y hora: "+when+"\nMesa: "+(tables[r.table_id]||"a confirmar")+"\nPersonas: "+r.guest_count+"\nCódigo de reserva: "+r.id+"\nAnticipo: $"+Number(policy?.reservation_min_amount||0).toLocaleString("es-AR")+" al alias "+(policy?.reservation_alias||"a confirmar")+"\nEstado del pago: "+pay+"\nTolerancia de llegada: "+(policy?.reservation_grace_minutes??30)+" minutos.\n¡Te esperamos!";return "https://wa.me/"+phone+"?text="+encodeURIComponent(msg)}
async function status(id:string,value:string){const {error}=await db.rpc("mesa_set_reservation_status",{p_reservation_id:id,p_status:value});setMessage(error?error.message:"Reserva actualizada.");if(!error)void refresh()}
return <main className="mesaBooking"><Link href="/mi-restaurante">← Mi restaurante</Link><h1>Reservas de mesas</h1><p>Administrá las reservas de tus clientes. Marcá «Llegó» cuando ocupen la mesa. La tolerancia la configura cada restaurante. Verificá los anticipos antes de informarle al cliente que recibió el pago.</p>{loading?<p>Cargando...</p>:!restaurants.length?<p>Ingresá con tu cuenta de dueño o administrador.</p>:<><label>Restaurante<select value={selected} onChange={e=>setSelected(e.target.value)}>{restaurants.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button onClick={()=>void refresh()}>Actualizar reservas</button><div className="mesaBookingList">{rows.map(r=><article key={r.id}><b>{new Date(r.starts_at).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires",dateStyle:"medium",timeStyle:"short"})}</b><p>{r.guest_name} · {r.guest_count} personas · Mesa {tables[r.table_id]||"—"}</p><p>WhatsApp: {r.guest_phone}</p><a className="mesaWhatsappButton" href={whatsappLink(r)} target="_blank" rel="noopener noreferrer">Enviar datos y estado de pago por WhatsApp ↗</a><p>Anticipo: <strong>{r.payment_status==="received"?"Transferencia recibida y verificada":r.payment_status==="rejected"?"Transferencia no acreditada":"Pendiente de verificar"}</strong></p><div className="mesaPaymentActions"><button type="button" disabled={r.payment_status==="received"} onClick={()=>void payment(r.id,"received")}>Marcar transferencia recibida</button><button type="button" disabled={r.payment_status==="pending"} onClick={()=>void payment(r.id,"pending")}>Marcar pendiente</button><button type="button" disabled={r.payment_status==="rejected"} onClick={()=>void payment(r.id,"rejected")}>No acreditada</button></div><strong>{r.status==="confirmed"&&new Date(r.starts_at).getTime()+(policy?.reservation_grace_minutes??30)*60000<Date.now()?"Tolerancia vencida · pendiente de liberar":r.status}</strong>{r.status==="confirmed"&&<div><button onClick={()=>void status(r.id,"seated")}>Llegó</button><button onClick={()=>void status(r.id,"expired")}>Liberar mesa</button><button onClick={()=>void status(r.id,"cancelled")}>Cancelar</button></div>}{r.status==="seated"&&<button onClick={()=>void status(r.id,"completed")}>Finalizar</button>}</article>)}</div>{!rows.length&&<p>Todavía no hay reservas para este restaurante.</p>}{message&&<p role="status">{message}</p>}</>}</main>}