"use client";
import {useEffect,useRef,useState} from "react";
import "./CircularCarousel.css";
export type CarouselItem={src:string;alt:string;title:string;subtitle?:string};
export default function CircularCarousel({items,cardWidth=240,aspectRatio=1,speed=14,gap=25,tilt=-5,perspective=2500,depthFade=.35,innerShade=.1,onItemClick}:{items:CarouselItem[];cardWidth?:number;aspectRatio?:number;speed?:number;gap?:number;tilt?:number;perspective?:number;depthFade?:number;innerShade?:number;onItemClick?:(item:CarouselItem,index:number)=>void}){
 const [position,setPosition]=useState(0),[width,setWidth]=useState(1100),[reduced,setReduced]=useState(false);
 const host=useRef<HTMLDivElement>(null),drag=useRef<{x:number;position:number;moved:boolean}|null>(null),last=useRef<number|null>(null),raf=useRef(0),positionRef=useRef(0);
 useEffect(()=>{const mq=window.matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>setReduced(mq.matches);sync();mq.addEventListener("change",sync);return()=>mq.removeEventListener("change",sync)},[]);
 useEffect(()=>{if(!host.current)return;const ro=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));ro.observe(host.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{if(reduced||items.length<2)return;const tick=(time:number)=>{if(last.current!==null&&!drag.current){positionRef.current+=(Math.min(time-last.current,50)/1000)*speed/55;setPosition(positionRef.current)}last.current=time;raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf.current);last.current=null}},[reduced,speed,items.length]);
 const n=items.length;const move=(v:number)=>{positionRef.current=v;setPosition(v)};
 const spacing=Math.max(cardWidth+Math.max(14,gap),Math.min(cardWidth+60,width/3));
 const visibleRadius=Math.min(3,Math.max(1,Math.ceil(width/spacing/2)));
 return <div ref={host} className="circular-carousel mesaCircularCarousel mesaCarouselCompact" tabIndex={0} aria-label="Restaurantes destacados, carrusel interactivo" onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();move(positionRef.current+(e.key==="ArrowLeft"?-1:1))}}} onPointerDown={e=>{drag.current={x:e.clientX,position:positionRef.current,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x;if(Math.abs(dx)>5)drag.current.moved=true;move(drag.current.position-Math.max(-n/2,Math.min(n/2,dx/spacing)))}} onPointerUp={e=>{if(drag.current){const d=drag.current;drag.current=null;if(!d.moved){const target=(e.target as HTMLElement).closest("[data-carousel-index]");if(target){const index=Number(target.getAttribute("data-carousel-index"));let delta=index-(Math.round(positionRef.current)%n+n)%n;if(delta>n/2)delta-=n;if(delta< -n/2)delta+=n;move(positionRef.current+delta);onItemClick?.(items[index],index)}}}}} onPointerCancel={()=>{drag.current=null}}>
 <div className="circular-carousel__stage">{items.map((item,i)=>{let offset=((i-position)%n+n)%n;if(offset>n/2)offset-=n;const abs=Math.abs(offset);if(abs>visibleRadius+.15)return null;const angle=Math.max(-30,Math.min(30,offset*7));const fade=depthFade*Math.min(1,abs/6);return <div key={i} data-carousel-index={i} className="mesaCircularCard" style={{width:cardWidth,height:cardWidth/aspectRatio,left:"50%",top:"50%",marginLeft:-cardWidth/2,marginTop:-cardWidth/(aspectRatio*2),transform:`translate3d(${offset*spacing}px,${Math.abs(offset)*3}px,${-abs*20}px) rotateY(${-angle}deg) rotateX(${tilt}deg) scale(${Math.max(.9,1-abs*.02)})`,opacity:abs>visibleRadius?0:Math.max(.45,1-fade),zIndex:100-Math.round(abs*10),borderRadius:12,pointerEvents:abs>visibleRadius?"none":"auto"}}><img src={item.src} alt={item.alt} draggable={false}/><div className="mesaCircularShade" style={{opacity:innerShade*Math.min(1,abs/5)}}/><div className="mesaCircularCaption"><b>{item.title}</b><small>{item.subtitle}</small></div></div>})}</div>
 <div className="mesaCircularControls"><button type="button" aria-label="Restaurante anterior" onClick={()=>move(positionRef.current-1)}>‹</button><span>{n} restaurantes para descubrir</span><button type="button" aria-label="Restaurante siguiente" onClick={()=>move(positionRef.current+1)}>›</button></div>
 </div>
}