"use client";
import {useEffect,useRef,useState} from "react";
import "./CircularCarousel.css";
export type CarouselItem={src:string;alt:string;title:string;subtitle?:string};
export default function CircularCarousel({items,cardWidth=240,aspectRatio=1,speed=14,gap=25,tilt=-5,perspective=2500,depthFade=.35,innerShade=.1,onItemClick}:{items:CarouselItem[];cardWidth?:number;aspectRatio?:number;speed?:number;gap?:number;tilt?:number;perspective?:number;depthFade?:number;innerShade?:number;onItemClick?:(item:CarouselItem,index:number)=>void}){
 const [angle,setAngle]=useState(0),[paused,setPaused]=useState(false),[width,setWidth]=useState(1100),[reduced,setReduced]=useState(false);
 const host=useRef<HTMLDivElement>(null),drag=useRef<{x:number;angle:number;moved:boolean}|null>(null),last=useRef<number|null>(null),raf=useRef(0),angleRef=useRef(0);
 useEffect(()=>{const mq=window.matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>setReduced(mq.matches);sync();mq.addEventListener("change",sync);return()=>mq.removeEventListener("change",sync)},[]);
 useEffect(()=>{if(!host.current)return;const ro=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));ro.observe(host.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{if(paused||reduced||items.length<2)return;const tick=(time:number)=>{if(last.current!==null){angleRef.current-=(Math.min(time-last.current,50)/1000)*speed;setAngle(angleRef.current)}last.current=time;raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf.current);last.current=null}},[paused,reduced,speed,items.length]);
 const n=items.length,step=360/Math.max(3,n),radius=Math.max(190,(cardWidth+gap)/(2*Math.sin(Math.PI/Math.max(3,n)))),fit=Math.min(1,width/(radius*2+cardWidth+60));
 const move=(a:number)=>{angleRef.current=a;setAngle(a)};
 return <div ref={host} className="circular-carousel mesaCircularCarousel" tabIndex={0} aria-label="Restaurantes destacados, carrusel interactivo" onMouseEnter={()=>{}} onMouseLeave={()=>{}} onFocus={()=>{}} onBlur={()=>{}} onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();move(angleRef.current+(e.key==="ArrowLeft"?step:-step))}}} onPointerDown={e=>{drag.current={x:e.clientX,angle:angleRef.current,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x;if(Math.abs(dx)>5)drag.current.moved=true;move(drag.current.angle+dx*.22)}} onPointerUp={e=>{if(drag.current){const moved=drag.current.moved;drag.current=null;if(!moved){const target=(e.target as HTMLElement).closest("[data-carousel-index]");if(target){const index=Number(target.getAttribute("data-carousel-index"));const desired=-index*step;move(desired+360*Math.round((angleRef.current-desired)/360));onItemClick?.(items[index],index)}}}setPaused(false)}} onPointerCancel={()=>{drag.current=null;setPaused(false)}}>
 <div className="circular-carousel__stage" style={{perspective:`${perspective}px`}}><div className="mesaCircularRing" style={{transform:`scale(${fit}) rotateX(${tilt}deg)`}}>{items.map((item,i)=>{const theta=i*step+angle,front=Math.cos(theta*Math.PI/180),fade=depthFade*Math.pow((1-front)/2,1.2);return <div key={item.src} data-carousel-index={i} className="mesaCircularCard" style={{width:cardWidth,height:cardWidth/aspectRatio,marginLeft:-cardWidth/2,marginTop:-cardWidth/(aspectRatio*2),transform:`rotateY(${i*step+angle}deg) translateZ(${radius}px) rotateY(${-angle}deg)`,opacity:Math.max(.3,1-fade),borderRadius:12}}><img src={item.src} alt={item.alt} draggable={false}/><div className="mesaCircularShade" style={{opacity:innerShade*Math.max(0,1-front)}}/><div className="mesaCircularCaption"><b>{item.title}</b><small>{item.subtitle}</small></div></div>})}</div></div>
 <div className="mesaCircularControls"><button type="button" aria-label="Restaurante anterior" onClick={()=>move(angleRef.current+step)}>‹</button><span>{n} restaurantes para descubrir</span><button type="button" aria-label="Restaurante siguiente" onClick={()=>move(angleRef.current-step)}>›</button></div>
 </div>
}