"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Bell,Check,ChevronRight,CircleDollarSign,Clock3,CreditCard,LayoutDashboard,LogIn,Menu,ReceiptText,Search,Sparkles,Star,UsersRound,UtensilsCrossed,WalletCards,X,Plus,ChefHat,MapPin,BarChart3} from "lucide-react";

const requests=[["Mesa 14","Pide la cuenta","hot"],["Mesa 07","Llamó al mozo","wait"],["Mesa 03","Sin solicitudes","ok"]];
const demo:any={
 Inicio:{title:"Buenas tardes.",cards:[["Facturación de hoy","$1.840.500","+18%"],["Atención promedio","1m 08s","↓ 14s"],["Propinas","$147.000","+9%"]]},
 Mesas:{title:"Mesas en vivo",cards:[["Ocupadas","18 / 24","75%"],["Esperando","2","Ahora"],["Cuenta pedida","3","Ahora"]]},
 Personal:{title:"Equipo en turno",cards:[["Juan","4,9 ★","8 mesas"],["Sofía","4,8 ★","6 mesas"],["Lucas","4,7 ★","4 mesas"]]},
 Reseñas:{title:"Experiencia",cards:[["Puntuación","4,8 ★","+0,2"],["Verificadas","312","100%"],["Esta semana","48","+12%"]]},
 Propinas:{title:"Propinas del equipo",cards:[["Hoy","$147.000","+9%"],["Juan","$42.000","4,9 ★"],["Sofía","$38.500","4,8 ★"]]}
};
export default function Home(){
 const [role,setRole]=useState<"owner"|"waiter">("owner"),[mobile,setMobile]=useState(false),[login,setLogin]=useState(false),[register,setRegister]=useState(false),[tab,setTab]=useState("Inicio"),[toast,setToast]=useState(""),[cursor,setCursor]=useState({x:-100,y:-100});
 useEffect(()=>{const m=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY});window.addEventListener("mousemove",m);return()=>window.removeEventListener("mousemove",m)},[]);
 const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),2200)};
 const d=demo[tab];
 return <main>
  <div className="customCursor" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}/><div className="cursorDot" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}/>
  {toast&&<div className="toast"><Check/> {toast}</div>}
  {(login||register)&&<div className="modalBg" onMouseDown={()=>{setLogin(false);setRegister(false)}}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>{setLogin(false);setRegister(false)}}><X/></button><div className="brand bigBrand"><i>M</i><b>Mesa</b></div><span className="tag">{register?"EMPECEMOS":"BIENVENIDO DE NUEVO"}</span><h2>{register?"Creá tu restaurante.":"Entrá a Mesa."}</h2><p>{register?"En minutos vas a tener mesas, equipo y menú listos para configurar.":"Volvé a tu operación en tiempo real."}</p>{register&&<input placeholder="Nombre del restaurante"/>}<input placeholder="Email"/><input type="password" placeholder="Contraseña"/><button className="primary wide" onClick={()=>notify(register?"Demo de alta lista. Falta conectar Supabase.":"Demo de acceso lista. Falta conectar Supabase.")}>{register?"Crear cuenta":"Ingresar"} <ArrowRight/></button><button className="modalSwitch" onClick={()=>{setRegister(!register);setLogin(register)}}>{register?"Ya tengo cuenta":"Quiero crear mi restaurante"}</button></div></div>}
  <header><a className="brand" href="#"><i>M</i><b>Mesa</b></a><nav><a href="#producto">Producto</a><a href="#experiencia">Experiencia</a><a href="#resenas">Reseñas</a><a href="#precio">Precio</a></nav><div className="headActions"><button className="ghost" onClick={()=>setLogin(true)}>Ingresar</button><button className="dark" onClick={()=>setRegister(true)}>Empezar <ArrowRight size={15}/></button><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button></div></header>
  {mobile&&<div className="mobileNav"><a href="#producto">Producto</a><a href="#experiencia">Experiencia</a><a href="#resenas">Reseñas</a><a href="#precio">Precio</a></div>}
  <section className="hero"><div className="blob accentBlob"/><div className="blob green"/>
   <div className="heroText"><div className="switch"><button className={role==="owner"?"on":""} onClick={()=>setRole("owner")}>Dueño</button><button className={role==="waiter"?"on":""} onClick={()=>setRole("waiter")}>Mozo</button></div><span className="tag">{role==="owner"?"LA OPERACIÓN, EN TIEMPO REAL":"UN TURNO MÁS SIMPLE"}</span><h1>{role==="owner"?<>Tu mesa pide.<br/>Tu equipo responde.</>:<>Atendé mejor.<br/>Corré menos.</>}</h1><p>{role==="owner"?"Mesas, mozos, cuenta en vivo, propinas y reseñas verificadas. Todo desde el celular, sin comprar hardware.":"Recibí llamados, tomá mesas, cargá consumos y cerrá el turno con todas tus métricas claras."}</p><div className="ctaRow"><button className="primary" onClick={()=>setRegister(true)}>{role==="owner"?"Crear mi restaurante":"Entrar como mozo"} <ArrowRight/></button><button className="outline" onClick={()=>document.querySelector("#experiencia")?.scrollIntoView()}>Ver cómo funciona</button></div><div className="trust"><span><Check/>Sin hardware extra</span><span><Check/>Mobile-first</span><span><Check/>QR por mesa</span></div></div>
   <div className="phoneWrap"><div className="float top"><Bell/> Mesa 14 te necesita</div><div className="phone"><div className="phoneTop"><div><small>Buenas noches</small><h3>Juan 👋</h3></div><em>● En turno</em></div><div className="mini"><div><b>8</b><small>mesas</small></div><div><b>4,9</b><small>⭐ atención</small></div><div><b>$42k</b><small>propinas</small></div></div><div className="requests">{requests.map(([a,b,c])=><button className="request" key={a} onClick={()=>notify(a+" · solicitud abierta")}><i className={c}/><div><b>{a}</b><small>{b}</small></div><ChevronRight/></button>)}</div><button className="phoneBtn" onClick={()=>notify("8 mesas asignadas a Juan")}>Ver todas las mesas</button></div><div className="float bottom"><ReceiptText/> Cuenta lista · $48.500</div></div>
  </section>
  <section className="stats" id="producto"><div><b>$1.840.500</b><span>facturado hoy</span></div><div><b>124</b><span>mesas atendidas</span></div><div><b>4,8 ★</b><span>experiencia</span></div></section>
  <section className="split section" id="experiencia"><div><span className="tag greenText">MESA INTELIGENTE</span><h2>El QR deja de ser un menú. Se convierte en servicio.</h2><p className="lead">Cada mesa tiene una sesión viva: puede llamar al mozo, ver su consumo, pedir la cuenta, pagar y valorar la experiencia.</p><div className="features">{[[Bell,"Llamar al mozo","La solicitud llega al mozo asignado en segundos."],[ReceiptText,"Ver mi cuenta","El cliente ve todo lo consumido en tiempo real."],[CreditCard,"Dividir y pagar","Cuenta lista, propina digital y cierre sin fricción."]].map(([Icon,t,d]:any)=><div className="feature" key={t}><i><Icon/></i><div><b>{t}</b><p>{d}</p></div></div>)}</div></div><div className="tableCard"><div className="tableTop"><b>Mesa 08</b><span><Check/> conectada</span></div><h3>¿Qué necesitás?</h3><div className="actions">{[[Bell,"Llamar al mozo"],[UtensilsCrossed,"Ver menú"],[ReceiptText,"Mi cuenta"],[WalletCards,"Pedir cuenta"]].map(([Icon,t]:any)=><button key={t} onClick={()=>notify(t+" · demo activada")}><Icon/><b>{t}</b></button>)}</div><div className="total"><span>Tu consumo</span><b>$34.600</b></div></div></section>
  <section className="dashSection section"><div className="center"><span className="tag">TU RESTAURANTE, CLARO</span><h2>Todo lo importante, sin ruido.</h2><p className="lead">Tocá el panel. Esta demo ya simula las áreas principales del sistema.</p></div><div className="dashboard"><aside><div className="brand"><i>M</i><b>Mesa</b></div>{[[LayoutDashboard,"Inicio"],[UtensilsCrossed,"Mesas"],[UsersRound,"Personal"],[Star,"Reseñas"],[CircleDollarSign,"Propinas"]].map(([Icon,t]:any)=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}><Icon/>{t}</button>)}</aside><div className="mobileTabs">{Object.keys(demo).map(t=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="dashMain"><div className="dashHead"><div><small>Operación en vivo · demo</small><h3>{d.title}</h3></div><button className="dark" onClick={()=>notify("Acción de demo creada")}>+ Nueva</button></div><div className="metrics">{d.cards.map((x:any,i:number)=><button className={"metric "+(i===0?"big":"")} key={x[0]} onClick={()=>notify(x[0]+": "+x[1])}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></button>)}</div><div className="activity"><div className="activityHead"><b>Actividad en vivo</b><span>● Ahora</span></div>{[["Mesa 12","Cuenta solicitada","hace 12 s"],["Mesa 04","Juan tomó la mesa","hace 28 s"],["Mesa 19","Nueva orden · $18.400","hace 1 min"]].map(x=><button className="activityRow" key={x[0]} onClick={()=>notify(x[0]+" · "+x[1])}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></button>)}</div></div></div></section>
  <section className="reviews section" id="resenas"><div><span className="tag greenText">RESEÑAS QUE VALEN</span><h2>Opiniones de gente que realmente comió ahí.</h2><p className="lead">La reseña nace después de una visita real. Mesa cerrada, identidad verificada y comentario asociado a la experiencia.</p><span className="verified"><Check/> Visita verificada</span></div><div className="reviewCard"><div className="stars">★★★★★</div><p>“Nos atendieron rapidísimo y la cuenta llegó sin tener que esperar al mozo.”</p><div className="reviewer"><i>TC</i><div><b>Tobias C.</b><small>Visita verificada · Mesa 11</small></div></div></div></section>
  <section className="section discover"><div className="center"><span className="tag">DESCUBRIR</span><h2>¿Qué querés comer hoy?</h2><p className="lead">Buscá por plato, no solamente por restaurante.</p></div><div className="search"><Search/><input placeholder="Milanesa napolitana, sushi, café..."/><button onClick={()=>notify("Búsqueda de demo lista")}>Buscar</button></div><div className="places">{[["El Club","Milanesas","4,8","$$"],["Don Pietro","Pastas","4,7","$$"],["Casa Nori","Sushi","4,9","$$$"]].map(x=><button className="place" key={x[0]} onClick={()=>notify(x[0]+" · perfil abierto")}><div className="art"><ChefHat/></div><div className="placeInfo"><div><b>{x[0]}</b><small>{x[1]}</small></div><strong><Star fill="currentColor"/>{x[2]} · {x[3]}</strong></div></button>)}</div></section>
  <section className="pricing section" id="precio"><div><span className="tag greenText">SIMPLE DE ACTIVAR</span><h2>Entrá rápido. Operá desde el primer día.</h2><p className="lead">Alta simple, activación inicial y mantenimiento mensual bajo.</p></div><div className="priceCard"><span>Activación inicial</span><b>$100.000</b><p>Configuración del restaurante, mesas, personal, menú y acceso completo.</p><hr/><div><span>Mantenimiento mensual</span><strong>Desde $20.000</strong></div><button className="primary wide" onClick={()=>setRegister(true)}>Crear mi restaurante <ArrowRight/></button></div></section>
  <section className="last"><div><span className="tag">MESA</span><h2>La atención de tu restaurante, en otro nivel.</h2><p>Sin aparatos. Sin vueltas. Desde el celular.</p><button className="primary" onClick={()=>setRegister(true)}>Empezar ahora <ArrowRight/></button></div></section>
  <footer><div className="brand"><i>M</i><b>Mesa</b></div><span>Producto gastronómico mobile-first.</span></footer>
 </main>
}