"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Bell,Check,ChevronRight,CircleDollarSign,Clock3,CreditCard,LayoutDashboard,LogIn,Menu,ReceiptText,Search,Sparkles,Star,UsersRound,UtensilsCrossed,WalletCards,X,Plus,ChefHat,MapPin,BarChart3} from "lucide-react";

const requests=[["Mesa 14","Pide la cuenta","hot"],["Mesa 07","Llamó al mozo","wait"],["Mesa 03","Sin solicitudes","ok"]];
const demo:any={
 Inicio:{title:"Buenas tardes.",cards:[["Facturación de hoy","$1.840.500","+18%"],["Atención promedio","1m 08s","↓ 14s"],["Propinas","$147.000","+9%"]]},
 Mesas:{title:"Mesas en vivo",cards:[["Ocupadas","18 / 24","75%"],["Esperando","2","Ahora"],["Cuenta pedida","3","Ahora"]]},
 Personal:{title:"Equipo en turno",cards:[["Juan","4,9 ★","8 mesas"],["Sofía","4,8 ★","6 mesas"],["Lucas","4,7 ★","4 mesas"]]},
 Reseñas:{title:"Experiencia",cards:[["Puntuación","4,8 ★","+0,2"],["Verificadas","312","100%"],["Esta semana","48","+12%"]]},
 Propinas:{title:"Propinas del equipo",cards:[["Hoy","$147.000","+9%"],["Juan","$42.000","4,9 ★"],["Sofía","$38.500","4,8 ★"]]}
};
export default function Home(){
 const [role,setRole]=useState<"owner"|"waiter">("owner"),[mobile,setMobile]=useState(false),[login,setLogin]=useState(false),[register,setRegister]=useState(false),[tab,setTab]=useState("Inicio"),[toast,setToast]=useState(""),[cursor,setCursor]=useState({x:-100,y:-100}),[waiterView,setWaiterView]=useState("home"),[guestView,setGuestView]=useState("home"),[demoApp,setDemoApp]=useState(false),[demoRole,setDemoRole]=useState<"owner"|"waiter">("owner");
 useEffect(()=>{const m=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY});window.addEventListener("mousemove",m);return()=>window.removeEventListener("mousemove",m)},[]);
 const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),2200)};
 const d=demo[tab];
 return <main>{demoApp&&<div className={"demoPortal "+(demoRole==="waiter"?"waiterPortal":"")}>
<div className="portalTop"><div className="brand"><i>M</i><b>Mesa · Demo</b></div><div className="roleToggle"><button className={demoRole==="owner"?"active":""} onClick={()=>setDemoRole("owner")}>Dueño</button><button className={demoRole==="waiter"?"active":""} onClick={()=>setDemoRole("waiter")}>Mozo</button></div><button onClick={()=>setDemoApp(false)}>Salir <X/></button></div>
{demoRole==="owner"?<div className="ownerApp"><aside className="realAside"><div><small>RESTAURANTE</small><h3>La Esquina</h3></div>{[[LayoutDashboard,"Inicio"],[UtensilsCrossed,"Mesas"],[UsersRound,"Personal"],[ReceiptText,"Pedidos"],[Star,"Reseñas"],[CircleDollarSign,"Propinas"],[BarChart3,"Reportes"]].map(([Icon,t]:any)=><button className={tab===t?"selected":""} key={t} onClick={()=>setTab(t)}><Icon/>{t}</button>)}</aside><section className="ownerContent"><div className="ownerHead"><div><small>Miércoles 7 de octubre · Operación en vivo</small><h2>{tab==="Inicio"?"Buenas tardes.":tab}</h2></div><button className="dark"><Plus/> Nueva acción</button></div>
{tab==="Inicio"&&<><div className="ownerMetrics"><article><span>Facturación hoy</span><b>$1.840.500</b><em>+18%</em></article><article><span>Mesas activas</span><b>18</b><em>de 24</em></article><article><span>Atención promedio</span><b>1m 08s</b><em>↓ 14s</em></article><article><span>Propinas</span><b>$147.000</b><em>+9%</em></article></div><div className="ownerColumns"><div className="ownerPanel"><div className="panelTitle"><b>Actividad en vivo</b><span>● Ahora</span></div>{[["Mesa 12","Cuenta solicitada","12 s"],["Mesa 04","Juan tomó la mesa","28 s"],["Mesa 19","Pedido $18.400","1 min"],["Mesa 08","Llamó a Sofía","2 min"]].map(x=><button className="liveRow" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></button>)}</div><div className="ownerPanel"><div className="panelTitle"><b>Equipo</b><span>6 en turno</span></div>{[["Juan","4,9 ★","8 mesas"],["Sofía","4,8 ★","6 mesas"],["Lucas","4,7 ★","4 mesas"]].map(x=><div className="staffRow" key={x[0]}><i>{x[0][0]}</i><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></div></>}
{tab==="Mesas"&&<div className="moduleGrid">{Array.from({length:12},(_,i)=><article className={"tableTile "+([2,6,9].includes(i)?"attention":"")} key={i}><span>MESA {String(i+1).padStart(2,"0")}</span><b>{[2,6,9].includes(i)?"Necesita atención":i%3===0?"Disponible":"Ocupada"}</b><small>{i%3===0?"Sin mozo":i%2?"Juan":"Sofía"} · {i%3===0?"—":"$"+(12400+i*1300).toLocaleString("es-AR")}</small></article>)}</div>}
{tab==="Personal"&&<div className="staffCards">{[["Juan Pérez","Mozo","4,9","$42.000","$286.400"],["Sofía Ruiz","Moza","4,8","$38.500","$244.800"],["Lucas Díaz","Mozo","4,7","$31.200","$198.200"]].map(x=><article key={x[0]}><i>{x[0][0]}</i><h3>{x[0]}</h3><span>{x[1]} · En turno</span><div><b>{x[2]} ★</b><small>Atención</small></div><div><b>{x[3]}</b><small>Propinas</small></div><div><b>{x[4]}</b><small>Facturado</small></div></article>)}</div>}
{tab==="Pedidos"&&<div className="kanban">{["Nuevos","Preparando","Listos"].map((col,j)=><div key={col}><h3>{col}</h3>{Array.from({length:3},(_,i)=><article key={i}><b>Mesa {j*3+i+2}</b><span>{i+1}× Milanesa · {i+2}× Bebida</span><small>{j===0?"hace 1 min":j===1?"8 min":"Listo para servir"}</small></article>)}</div>)}</div>}
{tab==="Reseñas"&&<div className="reviewsApp"><div className="scoreBig"><b>4,8</b><span>★★★★★</span><small>312 visitas verificadas</small></div>{[["★★★★★","Excelente atención de Juan, súper rápido.","María · Mesa 12"],["★★★★☆","Muy buena comida y sistema comodísimo.","Nicolás · Mesa 04"],["★★★★★","Pedimos la cuenta y llegó enseguida.","Carla · Mesa 19"]].map(x=><article key={x[2]}><b>{x[0]}</b><p>{x[1]}</p><small>✓ Visita verificada · {x[2]}</small></article>)}</div>}
{tab==="Propinas"&&<div className="tipsApp"><article className="tipHero"><span>Propinas hoy</span><b>$147.000</b><em>+9% vs ayer</em></article>{[["Juan","$42.000","29%"],["Sofía","$38.500","26%"],["Lucas","$31.200","21%"],["Otros","$35.300","24%"]].map(x=><div className="tipRow" key={x[0]}><b>{x[0]}</b><div><i style={{width:x[2]}}/></div><span>{x[1]}</span></div>)}</div>}
{tab==="Reportes"&&<div className="reportApp"><article><span>Ticket promedio</span><b>$14.842</b><em>+6,4%</em></article><article><span>Rotación de mesas</span><b>3,7×</b><em>+0,4</em></article><article><span>Hora pico</span><b>21:10</b><em>42 mesas/h</em></article><div className="fakeChart">{[42,66,48,82,70,95,78,62,88,73,55,38].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></div>}
</section></div>:
<div className="waiterApp"><div className="waiterPhone"><div className="waiterStatus"><div><small>Buenas noches</small><h2>Juan 👋</h2></div><span>● En turno</span></div><div className="waiterSummary"><article><b>8</b><small>mesas</small></article><article><b>4,9</b><small>atención</small></article><article><b>$42k</b><small>propinas</small></article></div><div className="waiterAlert urgent"><Bell/><div><b>Mesa 14</b><span>Pide la cuenta · hace 12 s</span></div><ChevronRight/></div><div className="waiterAlert"><Bell/><div><b>Mesa 07</b><span>Te llamó · hace 28 s</span></div><ChevronRight/></div><h3>Tus mesas</h3>{[["03","Preparando","$28.400"],["08","Comiendo","$34.600"],["11","Pedido servido","$19.800"],["18","Comiendo","$22.100"]].map(x=><button className="waiterTable" key={x[0]}><i>M{x[0]}</i><div><b>Mesa {x[0]}</b><span>{x[1]}</span></div><strong>{x[2]}</strong></button>)}<button className="endShift">Terminar turno</button><div className="waiterNav"><button><UtensilsCrossed/><small>Mesas</small></button><button><Bell/><small>Avisos</small></button><button><CircleDollarSign/><small>Propinas</small></button><button><Star/><small>Perfil</small></button></div></div></div>}</div>}<div className="cursorDot" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}}/>
  {toast&&<div className="toast"><Check/> {toast}</div>}
  {(login||register)&&<div className="modalBg" onMouseDown={()=>{setLogin(false);setRegister(false)}}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>{setLogin(false);setRegister(false)}}><X/></button><div className="brand bigBrand"><i>M</i><b>Mesa</b></div><span className="tag">{register?"EMPECEMOS":"BIENVENIDO DE NUEVO"}</span><h2>{register?"Creá tu restaurante.":"Entrá a Mesa."}</h2><p>{register?"En minutos vas a tener mesas, equipo y menú listos para configurar.":"Volvé a tu operación en tiempo real."}</p>{register&&<input placeholder="Nombre del restaurante"/>}<input placeholder="Email"/><input type="password" placeholder="Contraseña"/><button className="primary wide" onClick={()=>{setLogin(false);setRegister(false);setDemoApp(true)}}>{register?"Crear cuenta demo":"Ingresar a cuenta demo"} <ArrowRight/></button><button className="modalSwitch" onClick={()=>{setRegister(!register);setLogin(register)}}>{register?"Ya tengo cuenta":"Quiero crear mi restaurante"}</button></div></div>}
  <header><a className="brand" href="#"><i>M</i><b>Mesa</b></a><nav><a href="#producto">Producto</a><a href="#experiencia">Experiencia</a><a href="#resenas">Reseñas</a><a href="#precio">Precio</a></nav><div className="headActions"><button className="ghost" onClick={()=>setLogin(true)}>Ingresar</button><button className="dark" onClick={()=>setRegister(true)}>Empezar <ArrowRight size={15}/></button><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button></div></header>
  {mobile&&<div className="mobileNav"><a href="#producto">Producto</a><a href="#experiencia">Experiencia</a><a href="#resenas">Reseñas</a><a href="#precio">Precio</a></div>}
  <section className="hero"><div className="blob accentBlob"/><div className="blob green"/>
   <div className="heroText"><div className="switch"><button className={role==="owner"?"on":""} onClick={()=>setRole("owner")}>Dueño</button><button className={role==="waiter"?"on":""} onClick={()=>setRole("waiter")}>Mozo</button></div><span className="tag">{role==="owner"?"LA OPERACIÓN, EN TIEMPO REAL":"UN TURNO MÁS SIMPLE"}</span><h1>{role==="owner"?<>Tu mesa pide.<br/>Tu equipo responde.</>:<>Atendé mejor.<br/>Corré menos.</>}</h1><p>{role==="owner"?"Mesas, mozos, cuenta en vivo, propinas y reseñas verificadas. Todo desde el celular, sin comprar hardware.":"Recibí llamados, tomá mesas, cargá consumos y cerrá el turno con todas tus métricas claras."}</p><div className="ctaRow"><button className="primary" onClick={()=>setRegister(true)}>{role==="owner"?"Crear mi restaurante":"Entrar como mozo"} <ArrowRight/></button><button className="outline" onClick={()=>document.querySelector("#experiencia")?.scrollIntoView()}>Ver cómo funciona</button></div><div className="trust"><span><Check/>Sin hardware extra</span><span><Check/>Mobile-first</span><span><Check/>QR por mesa</span></div></div>
   <div className="phoneWrap"><div className="float top"><Bell/> Mesa 14 te necesita</div><div className="phone">
{waiterView==="home"?<><div className="phoneTop"><div><small>Buenas noches</small><h3>Juan 👋</h3></div><em>● En turno</em></div><div className="mini"><div><b>8</b><small>mesas</small></div><div><b>4,9</b><small>⭐ atención</small></div><div><b>$42k</b><small>propinas</small></div></div><div className="requests"><button className="request" onClick={()=>setWaiterView("bill14")}><i className="hot"/><div><b>Mesa 14</b><small>Pide la cuenta</small></div><ChevronRight/></button><button className="request" onClick={()=>setWaiterView("call7")}><i className="wait"/><div><b>Mesa 07</b><small>Llamó al mozo</small></div><ChevronRight/></button><button className="request" onClick={()=>setWaiterView("order3")}><i className="ok"/><div><b>Mesa 03</b><small>Pedido enviado · cocina</small></div><ChevronRight/></button></div><button className="phoneBtn" onClick={()=>setWaiterView("tables")}>Ver todas las mesas</button></>:
<div className="detailView"><button className="backBtn" onClick={()=>setWaiterView("home")}>← Volver</button>{waiterView==="bill14"&&<><span className="detailBadge">CUENTA SOLICITADA</span><h3>Mesa 14</h3><p>El cliente terminó y quiere pagar.</p><div className="ticket"><span>2 Milanesa napolitana <b>$28.000</b></span><span>2 Gaseosas <b>$7.000</b></span><span>1 Flan mixto <b>$6.500</b></span><hr/><span className="grand">Total <b>$41.500</b></span></div><button className="phoneBtn">Ir a cobrar</button></>}{waiterView==="call7"&&<><span className="detailBadge">LLAMADO</span><h3>Mesa 07</h3><p>Te están esperando hace 18 segundos.</p><div className="pulseBell"><Bell/></div><button className="phoneBtn">Tomar solicitud</button></>}{waiterView==="order3"&&<><span className="detailBadge">PEDIDO EN CURSO</span><h3>Mesa 03</h3><div className="timeline"><b>✓ Pedido tomado</b><b>✓ Enviado a cocina</b><span>○ Preparando</span></div></>}{waiterView==="tables"&&<><span className="detailBadge">TU TURNO</span><h3>Mesas activas</h3><div className="tableList">{["Mesa 03 · Preparando","Mesa 07 · Espera","Mesa 14 · Cuenta","Mesa 18 · Comiendo"].map(x=><button key={x}>{x}<ChevronRight/></button>)}</div><h4>Historial de hoy</h4><div className="history">12 mesas cerradas · $286.400 facturados</div></>}</div>}
</div><div className="float bottom"><ReceiptText/> Cuenta lista · $48.500</div></div>
  </section>
  <section className="stats" id="producto"><div><b>$1.840.500</b><span>facturado hoy</span></div><div><b>124</b><span>mesas atendidas</span></div><div><b>4,8 ★</b><span>experiencia</span></div></section>
  <section className="split section" id="experiencia"><div><span className="tag greenText">MESA INTELIGENTE</span><h2>El QR deja de ser un menú. Se convierte en servicio.</h2><p className="lead">Cada mesa tiene una sesión viva: puede llamar al mozo, ver su consumo, pedir la cuenta, pagar y valorar la experiencia.</p><div className="features">{[[Bell,"Llamar al mozo","La solicitud llega al mozo asignado en segundos."],[ReceiptText,"Ver mi cuenta","El cliente ve todo lo consumido en tiempo real."],[CreditCard,"Dividir y pagar","Cuenta lista, propina digital y cierre sin fricción."]].map(([Icon,t,d]:any)=><div className="feature" key={t}><i><Icon/></i><div><b>{t}</b><p>{d}</p></div></div>)}</div></div><div className="tableCard">{guestView==="home"?<><div className="tableTop"><b>Mesa 08</b><span><Check/> conectada</span></div><h3>¿Qué necesitás?</h3><div className="actions"><button onClick={()=>setGuestView("call")}><Bell/><b>Llamar al mozo</b></button><button onClick={()=>setGuestView("menu")}><UtensilsCrossed/><b>Ver menú</b></button><button onClick={()=>setGuestView("bill")}><ReceiptText/><b>Mi cuenta</b></button><button onClick={()=>setGuestView("pay")}><WalletCards/><b>Llamar para cobrar</b></button></div></>:<div className="guestDetail"><button className="backBtn light" onClick={()=>setGuestView("home")}>← Volver</button>{guestView==="call"&&<><div className="pulseBell guest"><Bell/></div><h3>Estamos avisándole a Juan</h3><p>Tu mozo recibió el llamado. Tiempo estimado: menos de 1 minuto.</p><span className="waiting">● Esperando al mozo…</span></>}{guestView==="menu"&&<><h3>Menú</h3><div className="menuItems">{[["Milanesa napolitana","Papas fritas · salsa · mozzarella","$14.000"],["Burger de la casa","Doble carne · cheddar · papas","$12.500"],["Ravioles","Salsa rosa · parmesano","$13.800"]].map(x=><div key={x[0]}><span><b>{x[0]}</b><small>{x[1]}</small></span><strong>{x[2]}</strong></div>)}</div></>}{guestView==="bill"&&<><h3>Tu cuenta</h3><div className="ticket lightTicket"><span>Milanesa napolitana <b>$14.000</b></span><span>Ravioles <b>$13.800</b></span><span>2 Gaseosas <b>$6.800</b></span><hr/><span className="grand">Total <b>$34.600</b></span></div></>}{guestView==="pay"&&<><h3>¿Listos para pagar?</h3><p>Juan va a acercarse con la cuenta de tu mesa.</p><button className="phoneBtn" onClick={()=>setGuestView("paywait")}>Sí, llamar para cobrar</button></>}{guestView==="paywait"&&<><div className="pulseBell guest"><Check/></div><h3>Juan ya fue avisado</h3><p>Quedate en la mesa. Tu mozo se acerca para realizar el cobro.</p></>}</div>}</div></section>
  <section className="dashSection section"><div className="center"><span className="tag">TU RESTAURANTE, CLARO</span><h2>Todo lo importante, sin ruido.</h2><p className="lead">Tocá el panel. Esta demo ya simula las áreas principales del sistema.</p></div><div className="dashboard"><aside><div className="brand"><i>M</i><b>Mesa</b></div>{[[LayoutDashboard,"Inicio"],[UtensilsCrossed,"Mesas"],[UsersRound,"Personal"],[Star,"Reseñas"],[CircleDollarSign,"Propinas"]].map(([Icon,t]:any)=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}><Icon/>{t}</button>)}</aside><div className="mobileTabs">{Object.keys(demo).map(t=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="dashMain"><div className="dashHead"><div><small>Operación en vivo · demo</small><h3>{d.title}</h3></div><button className="dark" onClick={()=>notify("Acción de demo creada")}>+ Nueva</button></div><div className="metrics">{d.cards.map((x:any,i:number)=><button className={"metric "+(i===0?"big":"")} key={x[0]} onClick={()=>notify(x[0]+": "+x[1])}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></button>)}</div><div className="activity"><div className="activityHead"><b>Actividad en vivo</b><span>● Ahora</span></div>{[["Mesa 12","Cuenta solicitada","hace 12 s"],["Mesa 04","Juan tomó la mesa","hace 28 s"],["Mesa 19","Nueva orden · $18.400","hace 1 min"]].map(x=><button className="activityRow" key={x[0]} onClick={()=>notify(x[0]+" · "+x[1])}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></button>)}</div></div></div></section>
  <section className="reviews section" id="resenas"><div><span className="tag greenText">RESEÑAS QUE VALEN</span><h2>Opiniones de gente que realmente comió ahí.</h2><p className="lead">La reseña nace después de una visita real. Mesa cerrada, identidad verificada y comentario asociado a la experiencia.</p><span className="verified"><Check/> Visita verificada</span></div><div className="reviewCard"><div className="stars">★★★★★</div><p>“Nos atendieron rapidísimo y la cuenta llegó sin tener que esperar al mozo.”</p><div className="reviewer"><i>TC</i><div><b>Tobias C.</b><small>Visita verificada · Mesa 11</small></div></div></div></section>
  <section className="section discover"><div className="center"><span className="tag">DESCUBRIR</span><h2>¿Qué querés comer hoy?</h2><p className="lead">Buscá por plato, no solamente por restaurante.</p></div><div className="search"><Search/><input placeholder="Milanesa napolitana, sushi, café..."/><button onClick={()=>notify("Búsqueda de demo lista")}>Buscar</button></div><div className="places">{[["El Club","Milanesas","4,8","$$"],["Don Pietro","Pastas","4,7","$$"],["Casa Nori","Sushi","4,9","$$$"]].map(x=><button className="place" key={x[0]} onClick={()=>notify(x[0]+" · perfil abierto")}><div className="art"><ChefHat/></div><div className="placeInfo"><div><b>{x[0]}</b><small>{x[1]}</small></div><strong><Star fill="currentColor"/>{x[2]} · {x[3]}</strong></div></button>)}</div></section>
  <section className="pricing section" id="precio"><div><span className="tag greenText">SIMPLE DE ACTIVAR</span><h2>Entrá rápido. Operá desde el primer día.</h2><p className="lead">Alta simple, activación inicial y mantenimiento mensual bajo.</p></div><div className="priceCard"><span>Activación inicial</span><b>$100.000</b><p>Configuración del restaurante, mesas, personal, menú y acceso completo.</p><hr/><div><span>Mantenimiento mensual</span><strong>Desde $20.000</strong></div><button className="primary wide" onClick={()=>setRegister(true)}>Crear mi restaurante <ArrowRight/></button></div></section>
  <section className="last"><div><span className="tag">MESA</span><h2>La atención de tu restaurante, en otro nivel.</h2><p>Sin aparatos. Sin vueltas. Desde el celular.</p><button className="primary" onClick={()=>setRegister(true)}>Empezar ahora <ArrowRight/></button></div></section>
  <footer><div className="brand"><i>M</i><b>Mesa</b></div><span>Producto gastronómico mobile-first.</span></footer>
 </main>
}