"use client";
import {useEffect,useRef,useState} from "react";
import {Star} from "lucide-react";
import "./PeekRating.css";

type Props={value?:number;defaultValue?:number;onChange?:(value:number)=>void;count?:number;labels?:string[];activeColor?:string;idleColor?:string;size?:number;lift?:number;magnify?:number;showTip?:boolean;allowClear?:boolean;readOnly?:boolean;ariaLabel?:string;className?:string};
export default function PeekRating({value:controlled,defaultValue=0,onChange,count=5,labels=["Mala","Regular","Buena","Muy buena","Excelente"],activeColor="#f5b400",idleColor="#9b938c",size=34,lift=8,magnify=1.15,showTip=true,allowClear=false,readOnly=false,ariaLabel="Calificación",className=""}:Props){
 const [internal,setInternal]=useState(defaultValue),[hover,setHover]=useState<number|null>(null);const refs=useRef<(HTMLButtonElement|null)[]>([]);const value=Math.max(0,Math.min(count,controlled??internal));const shown=hover??value;const choose=(n:number)=>{if(readOnly)return;const next=allowClear&&n===value?0:n;if(controlled===undefined)setInternal(next);onChange?.(next);const el=refs.current[next-1];if(el&&!window.matchMedia("(prefers-reduced-motion: reduce)").matches){el.animate([{transform:"scale(1)"},{transform:"scale(1.3)"},{transform:"scale(1)"}],{duration:320,easing:"cubic-bezier(.23,1,.32,1)"})}};
 return <div className={`mesaPeekRating ${className}`} role={readOnly?"img":"radiogroup"} aria-label={readOnly?`${value} de ${count} estrellas`:ariaLabel} style={{"--peek-size":`${size}px`,"--peek-active":activeColor,"--peek-idle":idleColor,"--peek-lift":`${lift}px`,"--peek-magnify":magnify} as React.CSSProperties} onMouseLeave={()=>setHover(null)}>{Array.from({length:count},(_,i)=>{const n=i+1;return <button key={i} type="button" ref={el=>{refs.current[i]=el}} role={readOnly?undefined:"radio"} aria-checked={readOnly?undefined:value===n} aria-label={`${n} estrellas · ${labels[i]||n}`} disabled={readOnly} className={`mesaPeekStar ${n<=shown?"isLit":""} ${hover===n?"isHovered":""}`} onPointerEnter={e=>{if(e.pointerType==="mouse"&&!readOnly)setHover(n)}} onFocus={()=>{if(!readOnly)setHover(n)}} onBlur={()=>setHover(null)} onClick={()=>choose(n)} onKeyDown={e=>{if(["ArrowRight","ArrowUp","ArrowLeft","ArrowDown","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?1:e.key==="End"?count:Math.max(1,Math.min(count,value+(e.key==="ArrowRight"||e.key==="ArrowUp"?1:-1)));choose(next);refs.current[next-1]?.focus()}}}><span className="mesaPeekGlyph"><Star size={size} fill="currentColor" strokeWidth={1.6}/></span>{showTip&&hover===n&&!readOnly&&<span className="mesaPeekTip">{labels[i]||n}</span>}</button>})}</div>
}
