"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import Link from "next/link";
const db=createClient("https://oietadzixpglmkiokihj.supabase.co","sb_publishable_lbPUme-0Y7hjHWdcdGS2nA_Miy8rnzx");
type Table={id:string;number:number;salon_name:string;salon_id?:string;pos_x:number|null;pos_y:number|null};
function todayArgentina(){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const part=(type:string)=>parts.find(x=>x.type===type)?.value||"";return part("year")+"-"+part("month")+"-"+part("day")}
export default function Reservar({params}:{params:{id:string}}){const [salons,setSalons]=useState<{id:string;name:string;objects:{id:string;name:string;type:string;x:number;y:number}[]}[]>([]),[salon,setSalon]=useState(""),[terms,setTerms]=useState<{reservation_alias:string;reservation_min_amount:number}|null>(null),[place,setPlace]=useState<any>(null),[tables,setTables]=useState<Table[]>([]),[unavailable,setUnavailable]=useState<string[]>([]),[table,setTable]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState("20:00"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[guests,setGuests]=useState(2),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{db.rpc("mesa_directory_booking_terms",{p_restaurant_id:params.id}).then(({data})=>setTerms(data?.[0]||null));db.rpc("mesa_directory_list").then(({data})=>setPlace((data||[]).find((p:any)=>p.id===params.id)||null));db.rpc("mesa_public_salon_layout",{p_restaurant_id:params.id}).then(({data})=>{setSalons(data||[]);if(data?.length)setSalon(data[0].id)});db.rpc("mesa_public_tables",{p_restaurant_id:params.id}).then(({data})=>setTables(data||[]))},[params.id]);
useEffect(()=>{if(!date||!time){setUnavailable([]);return}db.rpc("mesa_unavailable_tables",{p_restaurant_id:params.id,p_starts_at:new Date(date+"T"+time+":00-03:00").toISOString()}).then(({data})=>setUnavailable((data||[]).map((r:any)=>r.table_id)))},[params.id,date,time]);
const slots=date&&place?(place.weekly_hours?.[String(new Date(date+"T12:00:00").getDay())]||[]):[];
const times=Array.from({length:48},(_,i)=>String(Math.floor(i/2)).padStart(2,"0")+":"+(i%2?"30":"00")).filter(t=>slots.some((s:string[])=>t>=s[0]&&t<s[1]));
async function book(){if(!table||!date||!time||!name.trim()||!phone.trim()||unavailable.includes(table)){setMessage("Completá todos los campos y elegí una mesa.");return}setBusy(true);setMessage("");const local=new Date(date+"T"+time+":00-03:00").toISOString();const {data,error}=await db.rpc("mesa_book_table",{p_restaurant_id:params.id,p_table_id:table,p_guest_name:name,p_guest_phone:phone,p_guest_count:guests,p_starts_at:local});setBusy(false);setMessage(error?"No se pudo reservar: "+error.message:"Reserva registrada. Código: "+data+". Transferí el anticipo al alias indicado y coordiná la verificación con el restaurante. La transferencia NO está verificada por MESA.") }
return <main className="mesaBooking"><Link href="/explorar">← Volver a Explorar MESA</Link><h1>Reservar mesa {place?"en "+place.name:""}</h1>{!place?<p>Buscando restaurante...</p>:!place.accepts_reservations?<p>Este restaurante no acepta reservas online.</p>:<><p>Elegí una fecha, un horario de atención y una mesa del salón. La reserva dura 2 horas y tiene 30 minutos de tolerancia para presentarte.</p><div className="mesaBookingForm"><label>Fecha<input type="date" min={todayArgentina()} value={date} onChange={e=>{setDate(e.target.value);setTime("");setTable("")}}/></label><label>Horario<select value={time} onChange={e=>{setTime(e.target.value);setTable("")}}><option value="">Elegí un horario</option>{times.map(t=><option key={t}>{t}</option>)}</select></label><h2>Seleccioná una mesa</h2><p>Plano de mesas habilitadas para reservas. La distribución operativa puede incluir elementos que todavía no se muestran aquí.</p><div className="mesaSalonTabs">{salons.map(s=><button key={s.id} className={salon===s.id?"chosen":""} onClick={()=>{setSalon(s.id);setTable("")}}>{s.name}</button>)}</div><div className="mesaBookingMap">{salons.find(s=>s.id===salon)?.objects?.map(o=><div key={o.id} className="mesaSalonObject" style={{left:o.x+"%",top:o.y+"%"}}>{o.name||o.type}</div>)}{tables.filter(t=>!salon||t.salon_id===salon).map(t=><button type="button" disabled={unavailable.includes(t.id)} style={t.pos_x!=null&&t.pos_y!=null?{position:"absolute",left:Math.max(5,Math.min(85,Number(t.pos_x)))+"%",top:Math.max(5,Math.min(85,Number(t.pos_y)))+"%"}:{}} className={table===t.id?"chosen":""} onClick={()=>setTable(t.id)} key={t.id}>Mesa {t.number}<small>{unavailable.includes(t.id)?"Ocupada":t.salon_name}</small></button>)}</div>{!tables.length&&<p>El restaurante todavía no habilitó mesas en su salón.</p>}{terms&&<div className="mesaDeposit"><strong>Anticipo requerido para reservar</strong><p>Importe mínimo: <b>${Number(terms.reservation_min_amount||0).toLocaleString("es-AR")}</b></p><p>Alias para transferir: <b>{terms.reservation_alias}</b></p><small>El restaurante debe verificar la transferencia. No envíes dinero si los datos no coinciden con los confirmados por el local.</small></div>}<label>Nombre<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Teléfono de contacto<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={35}/></label><label>Personas<input type="number" min={1} max={30} value={guests} onChange={e=>setGuests(Number(e.target.value))}/></label><button disabled={busy||!date||!time||!table||!terms?.reservation_alias||!(Number(terms?.reservation_min_amount)>0)} onClick={book}>{busy?"Confirmando...":"Confirmar reserva"}</button>{message&&<p role="status">{message}</p>}</div></>}</main>}